### ISSUE TITLE
How to override entities

### ISSUE THREAD

**Issue by mistris** [Discutea/DForumBundle#16]
Hi!

How can I override entities of this bundle?
I want to:

- add some fields to `Topic` entity
- add fulltext indexes for `Topic.title` and `Post.content`

I tried to make my own Forum bundle. I have already overridden controllers and views, but entities just don't work as expected - indexes are not added after schema update (if I don't specify the table name in my extended entity "Post").

But if I specify the same table name `"df_post"` like this 
![image](https://cloud.githubusercontent.com/assets/3584575/21797086/a6ff5098-d715-11e6-8aeb-87f95cdef419.png)

then during schema update I get the following error `"The table name 'df_post' already exists"` although the DB doesn't contain this table.

I also tried to put the following lines in my `config.yml`:
```
doctrine:
    orm:
       resolve_target_entities:
          Discutea\DForumBundle\Entity\Post: ForumBundle\Entity\Post
```

but it didn't help.

Can anyone please help me?
